<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.37.1" />
  <meta name="author" content="Aaron Shaffer">

  
  
  
  
    
      
    
  
  <meta name="description" content="ISLR Ch4 Exercises #5, #13   We now examine the differences between LDA and QDA.    \((a)\) If the Bayes decision boundary is linear, do we expect LDA or QDA to perform better on the training set? On the test set?   On the training set of data you would expect LDA to perform better than the QDA if the decision boundary is linear and there are relatively few training observations.">

  
  <link rel="alternate" hreflang="en-us" href="/post/islr_ch4/">

  


  

  
  
  <meta name="theme-color" content="#0095eb">
  
  
  
  
    
  
  
    
    
      
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">
      
    
  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha512-6MXa8B6uaO18Hid6blRMetEIoPqHf7Ux1tnyIQdpt9qI5OACx7C+O3IVTr98vwGnlcg0LOLa02i9Y1HpVhlfiw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.1/css/academicons.min.css" integrity="sha512-NThgw3XKQ1absAahW6to7Ey42uycrVvfNfyjqcFNgCmOCQ5AR4AO0SiXrN+8ZtYeappp56lk1WtvjVmEa+VR6A==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">
  
  
  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700%7cRoboto:400,400italic,700%7cRoboto&#43;Mono">
  
  <link rel="stylesheet" href="/styles.css">
  
  <link rel="stylesheet" href="/css/sours.css">
  

  

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Aaron&#39;s Statistics Blog">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Aaron&#39;s Statistics Blog">
  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/islr_ch4/">

  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@ClassicSours">
  <meta property="twitter:creator" content="@ClassicSours">
  
  <meta property="og:site_name" content="Aaron&#39;s Statistics Blog">
  <meta property="og:url" content="/post/islr_ch4/">
  <meta property="og:title" content="ISLR Chapter 4 | Aaron&#39;s Statistics Blog">
  <meta property="og:description" content="ISLR Ch4 Exercises #5, #13   We now examine the differences between LDA and QDA.    \((a)\) If the Bayes decision boundary is linear, do we expect LDA or QDA to perform better on the training set? On the test set?   On the training set of data you would expect LDA to perform better than the QDA if the decision boundary is linear and there are relatively few training observations.">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2018-03-12T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2018-03-12T00:00:00&#43;00:00">
  

  

  <title>ISLR Chapter 4 | Aaron&#39;s Statistics Blog</title>

</head>
<body id="top" data-spy="scroll" data-target="#toc" data-offset="71" >

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="/">Aaron&#39;s Statistics Blog</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      
      <ul class="nav navbar-nav navbar-right">
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="/#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="/#projects">
            
            <span>Projects</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="/#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        
      

      
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  


  <div class="article-container">
    <h1 itemprop="name">ISLR Chapter 4</h1>

    

<div class="article-metadata">

  <span class="article-date">
    
    <time datetime="2018-03-12 00:00:00 &#43;0000 UTC" itemprop="datePublished dateModified">
      Mar 12, 2018
    </time>
  </span>
  <span itemscope itemprop="author publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Aaron Shaffer">
  </span>

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    5 min read
  </span>
  

  
  

  
  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fa fa-folder"></i>
    
    <a href="/categories/r">r</a
    >, 
    
    <a href="/categories/islr">ISLR</a
    >
    
  </span>
  
  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=ISLR%20Chapter%204&amp;url=%2fpost%2fislr_ch4%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2fislr_ch4%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2fislr_ch4%2f&amp;title=ISLR%20Chapter%204"
         target="_blank" rel="noopener">
        <i class="fa fa-linkedin"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2fislr_ch4%2f&amp;title=ISLR%20Chapter%204"
         target="_blank" rel="noopener">
        <i class="fa fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=ISLR%20Chapter%204&amp;body=%2fpost%2fislr_ch4%2f">
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>


    <div class="article-style" itemprop="articleBody">
      <h1>
ISLR Ch4 Exercises #5, #13
</h1>
<h3>
<ol start="5" style="list-style-type: decimal">
<li>We now examine the differences between LDA and QDA.</li>
</ol>
</h3>
<h4>
<span class="math inline">\((a)\)</span> If the Bayes decision boundary is linear, do we expect <code>LDA</code> or <code>QDA</code> to perform better on the training set? On the test set?
</h4>
<blockquote>
<p>On the training set of data you would expect <code>LDA</code> to perform better than the <code>QDA</code> if the decision boundary is linear and there are relatively few training observations. Otherwise <code>QDA</code> will perform better.</p>
</blockquote>
<blockquote>
<p>On the test set of data LDA will be better if the common correlation between <code>X_1</code> and <code>X_2</code> have and the bayes decision boundary is linear.</p>
</blockquote>
<h4>
<span class="math inline">\((b)\)</span> If the Bayes decision boundary is non-linear, do we expect <code>LDA</code> or <code>QDA</code> to perform better on the training set? On the test set?
</h4>
<blockquote>
<p>On the training set of data <code>QDA</code> will perform better than <code>LDA</code> unless there are very few observations</p>
</blockquote>
<blockquote>
<p>On the test set of data <code>QDA</code> will perform better</p>
</blockquote>
<h4>
<span class="math inline">\((c)\)</span> In general, as the sample size <code>n</code> increases, do we expect the test prediction accuracy of <code>QDA</code> relative to <code>LDA</code> to improve, decline, or be unchanged? Why?
</h4>
<blockquote>
<p>We expect the relative prediction accuracy of <code>QDA</code> model to improve because it is more flexible than the <code>LDA</code> model. This flexibility allows <code>QDA</code> to outpeform LDA because once <code>N</code> becomes large enough variance of the classifier is not a major concern, And with enough <code>K's</code> the assumption of a common covariance matrix for the <code>K</code> classes is unrealistic.</p>
</blockquote>
<h4>
<span class="math inline">\((d)\)</span> <code>True</code> or <code>False</code>: Even if the Bayes decision boundary for a given problem is linear, we will probably achieve a superior test error rate using <code>QDA</code> rather than <code>LDA</code> because <code>QDA</code> is flexible enough to model a linear decision boundary. Justify your answer.
</h4>
<blockquote>
<p><code>True</code>, <code>LDA</code> is much more affected by the variance in the observations than <code>QDA</code> so unless there is extremely low variance in the data or very few observations <code>QDA</code> should outpeform <code>LDA</code></p>
</blockquote>
<h3>
<ol start="13" style="list-style-type: decimal">
<li>Using the Boston data set, fit classification models in order to predict whether a given suburb has a crime rate above or below the median. Explore logistic regression, LDA, and KNN models using various subsets of the predictors. Describe your findings.</li>
</ol>
</h3>
<pre class="r"><code>Boston &lt;- MASS::Boston %&gt;% as.data.frame()
crim &lt;- Boston %$% ifelse(crim &lt; median(crim), 0 , 1)
Boston$crim.rate &lt;- crim
X &lt;- split(Boston, rep(1:2, nrow(Boston)/2))
Train &lt;- as.data.frame(X[[1]])
Test  &lt;- as.data.frame(X[[2]])</code></pre>
<h4>
Logisitc Regeression
</h4>
<pre class="r"><code>fit.glm &lt;- glm(crim.rate ~ . - crim - crim.rate, 
               data=Boston,
               family=binomial,
               subset=rownames(Train))

probs &lt;- predict(fit.glm, Test, type = &quot;response&quot;)
pred.glm &lt;- ifelse(probs &lt; .5, 0,1)
table(pred.glm, Test$crim.rate)</code></pre>
<pre><code>##         
## pred.glm   0   1
##        0 116  11
##        1  12 114</code></pre>
<pre class="r"><code>mean(pred.glm != Test$crim.rate)</code></pre>
<pre><code>## [1] 0.09090909</code></pre>
<blockquote>
<p>Logistic regression over boston using every other row as training/testing data and all predictors resulted in a test error rate of 9.09%</p>
</blockquote>
<pre class="r"><code>fit.glm &lt;- glm(crim.rate ~ 
                 indus + age+ dis + rad + ptratio + black + nox + indus*age,  
               data=Boston,
               family=binomial,
               subset=rownames(Train))

probs &lt;- predict(fit.glm, Test, type = &quot;response&quot;)
pred.glm &lt;- ifelse(probs &lt; .5, 0,1)
table(pred.glm, Test$crim.rate)</code></pre>
<pre><code>##         
## pred.glm   0   1
##        0 117   9
##        1  11 116</code></pre>
<pre class="r"><code>mean(pred.glm != Test$crim.rate)</code></pre>
<pre><code>## [1] 0.07905138</code></pre>
<blockquote>
<p>A second logistic regression model using <span class="math inline">\(indus^1\)</span> <span class="math inline">\(age^2\)</span> <span class="math inline">\(dis^3\)</span> <span class="math inline">\(ptratio^4\)</span> <span class="math inline">\(black^5\)</span> <span class="math inline">\(nox^6\)</span> and <span class="math inline">\(indus*age^7\)</span> resulted in a test error rate of 7.91%</p>
</blockquote>
<ol style="list-style-type: decimal">
<li><p><code>indus</code> : proportion of non-retail business acres per town.</p></li>
<li><p><code>age</code> : proportion of owner-occupied units built prior to 1940.</p></li>
<li><p><code>dis</code> : weighted mean of distances to five Boston employment centres.</p></li>
<li><p><code>ptratio</code> : pupil-teacher ratio by town.</p></li>
<li><p><code>black</code> : <span class="math inline">\(1000(Bk - 0.63)^2\)</span> where <code>Bk</code> is the proportion of blacks by town.</p></li>
<li><p><code>nox</code> : nitrogen oxides concentration (parts per 10 million).</p></li>
<li><p><code>indus*age</code> : the interaction between <code>indus</code> and <code>age</code></p></li>
</ol>
<h4>
LDA
</h4>
<pre class="r"><code>lda.fit &lt;- MASS::lda(crim.rate ~ . - crim - crim.rate, 
               data=Boston,
               family=binomial,
               subset=rownames(Train))

probs &lt;- predict(lda.fit, Test, model = &quot;response&quot;)
table(probs$class, Test$crim.rate)</code></pre>
<pre><code>##    
##       0   1
##   0 124  28
##   1   4  97</code></pre>
<pre class="r"><code>mean(probs$class != Test$crim.rate)</code></pre>
<pre><code>## [1] 0.1264822</code></pre>
<blockquote>
<p>LDA over boston using every other row as training/testing data and all predictors resulted in a test error rate of 12.65%</p>
</blockquote>
<pre class="r"><code>lda.fit &lt;-  MASS::lda(crim.rate ~ 
                        indus + age + dis + rad + ptratio + black + nox + indus*age,  
               data=Boston,
               family=binomial,
               subset=rownames(Train))

probs &lt;- predict(lda.fit, Test, model = &quot;response&quot;)
table(probs$class, Test$crim.rate)</code></pre>
<pre><code>##    
##       0   1
##   0 122  29
##   1   6  96</code></pre>
<pre class="r"><code>mean(probs$class != Test$crim.rate)</code></pre>
<pre><code>## [1] 0.1383399</code></pre>
<blockquote>
<p>A second LDA over boston using the same predictors as the second GLM resulted in a test error rate of 15.02%</p>
</blockquote>
<h4>
KNN
</h4>
<pre class="r"><code>set.seed(1)
best &lt;- .Machine$integer.max
best.i &lt;- 0
worst &lt;- 0
worst.i &lt;- 0
for(i in 1:253){
  k &lt;- class::knn(Train,Test, Train$crim.rate, k = i)
  error &lt;- 100 * mean(k != Train$crim.rate)
  if(error &lt; 10) {
    cat(sprintf(&quot;&lt;h5&gt;K == %d&lt;/h5&gt;&quot;,i))
    cat(pander(table(k,Test$crim.rate)))
    cat(sprintf(&quot;&lt;p&gt;When K == %d, KNN has a test error rate of %.2f%%&lt;/p&gt;&quot;,i,error))
  }
  if(error &lt; best) {
    best &lt;- error
    best.i &lt;- i    
  }
  if(error &gt; worst) {
    worst &lt;- error
    worst.i &lt;- i    
  }
}</code></pre>
<h5>
K == 1
</h5>
<table style="width:29%;">
<colgroup>
<col width="12%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">0</th>
<th align="center">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>0</strong></td>
<td align="center">116</td>
<td align="center">10</td>
</tr>
<tr class="even">
<td align="center"><strong>1</strong></td>
<td align="center">12</td>
<td align="center">115</td>
</tr>
</tbody>
</table>
<p>
When K == 1, KNN has a test error rate of 8.30%
</p>
<h5>
K == 3
</h5>
<table style="width:29%;">
<colgroup>
<col width="12%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">0</th>
<th align="center">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>0</strong></td>
<td align="center">116</td>
<td align="center">11</td>
</tr>
<tr class="even">
<td align="center"><strong>1</strong></td>
<td align="center">12</td>
<td align="center">114</td>
</tr>
</tbody>
</table>
<p>
When K == 3, KNN has a test error rate of 9.49%
</p>
<h5>
K == 4
</h5>
<table style="width:29%;">
<colgroup>
<col width="12%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">0</th>
<th align="center">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>0</strong></td>
<td align="center">117</td>
<td align="center">11</td>
</tr>
<tr class="even">
<td align="center"><strong>1</strong></td>
<td align="center">11</td>
<td align="center">114</td>
</tr>
</tbody>
</table>
<p>
When K == 4, KNN has a test error rate of 9.88%
</p>
<h5>
When K == 1, KNN performed the best with a test error rate of 8.30%
</h5>
<h5>
When K == 251, KNN performed the worst with a test error rate of 49.41%
</h5>

    </div>

    


<div class="article-tags">
  
  <a class="btn btn-primary btn-outline" href="/tags/homework">homework</a>
  
  <a class="btn btn-primary btn-outline" href="/tags/r-markdown">R Markdown</a>
  
</div>




    
    
    <div class="article-widget">
      <div class="hr-light"></div>
      <h3>Related</h3>
      <ul>
        
        <li><a href="/post/islr_ch3/">ISLR Ch 3</a></li>
        
        <li><a href="/post/islr_ch2/">ISLR Ch2</a></li>
        
        <li><a href="/project/gapminder/">gapminder</a></li>
        
        <li><a href="/project/homework2/">homework2</a></li>
        
        <li><a href="/post/make-for-r/">Make File in R</a></li>
        
      </ul>
    </div>
    

    

    


  </div>
</article>

<footer class="site-footer">
  <div class="container">
    <p class="powered-by">

      &copy; 2018 &middot; 

      Powered by the
      <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
      <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close btn-large" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Cite</h4>
      </div>
      <div>
        <pre><code class="modal-body tex"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary btn-outline js-copy-cite" href="#" target="_blank">
          <i class="fa fa-copy"></i> Copy
        </a>
        <a class="btn btn-primary btn-outline js-download-cite" href="#" target="_blank">
          <i class="fa fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    

    

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha512-3P8rXCuGJdNZOnUx/03c1jOTnMn3rP63nBip5gOP2qmUh5YAdVAvFZ1E+QLZZbC1rtMrQb+mah3AfYW11RUrWA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha512-iztkobsvnjKfAtTNdHkGVjAYTrrtlC7mGp/54c40wowO7LhURYl3gVzzcEqGl/qKXQltJ2HwMrdLcNUdo+N/RQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>
    
    
    <script src="/js/hugo-academic.js"></script>
    

    
    
      
      
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
      

      

      

      <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
    </script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML" integrity="sha512-tOav5w1OjvsSJzePRtt2uQPFwBoHt1VZcUq8l8nm5284LEKE9FSJBQryzMBzHxY5P0zRdNqEcpLIRVYFNgu1jw==" crossorigin="anonymous"></script>
    
    

  </body>
</html>

