---
title: ISLR Ch 3
author: Aaron Shaffer
date: '2018-03-05'
slug: islr_ch3
categories:
  - r
  - ISLR
tags:
  - homework
  - R Markdown
summary: "ISLR Ch3 Exercises #4, #15"
header-includes:
  \usepackage[dvipsnames]{xcolor}
output: html_document
---

<h1> ISLR Ch3 Exercises #4, #15 </h1>

<h3> 
  4. I collect a set of data (`n = 100` observations) containing a single predictor and a quantitative response. I then fit a linear regression model to the data, as well as a separate cubic regression, i.e. $Y = \beta_{0}+\beta_{1}X+\beta_{2}X^{2}+\beta_{3}X^{3}+\epsilon$. 
</h3>

<h4> $(a)$ Suppose that the true relationship between `X` and `Y` is `linear`, i.e. $Y = \beta_0 + \beta_{1}X + \epsilon$. Consider the training residual sum of squares `(RSS)` for the linear regression, and also the training `RSS` for the cubic regression. Would we expect one to be lower than the other, would we expect them to be the same, or is there not enough information to tell? Justify your answer.</h4>

> We would expect `RSS` to be lower for the `cubic regression`.  This model is much more flexible and will allow for the line to be much closer to the training data set.

<h4> $(b)$ Answer $(a)$ using test rather than training RSS. </h4>

> We would expect the `RSS` to be lower for the `linear regression`.  Since the true underlying relationship is linear the cubic regression is more likely to overpredict on the training set and therefor have a higher `RSS` for the test set.

<h4> $(c)$ Suppose that the true relationship between `X` and `Y` is not linear, but we don’t know how far it is from linear. Consider the training RSS for the linear regression, and also the training RSS for the cubic regression. Would we expect one to be lower than the other, would we expect them to be the same, or is there not enough information to tell? Justify your answer. </h4>

> The `cubic regression` model will perform better on the training set because it has greater degrees of freedom and the model is also non linear.

<h4> $(d)$ Answer $(c)$ using test rather than training RSS. </h4>

> It is very possible that the `cubic regression` model will perform better on the test rather than the training data than the `linear regression` model but.  If the `cubic regression` model is over trained on the training data then the `linear regerssion` model might strike a better line through the test data data and have a lower `RSS`


<h3> 15. This problem involves the `Boston` data set, which we saw in the lab for this chapter. We will now try to predict `per capita crime rate` using the other variables in this data set. In other words, `per capita crime rate` is the `response`, and the other variables are the predictors. </h3>

```{r}
Boston <- MASS::Boston
```

<h4>$(a)$ For each predictor, fit a simple linear regression model to predict the response. Describe your results. In which of the models is there a statistically significant association between the predictor and the response? Create some plots to back up your assertions.</h4>

<h4>$(b)$ Fit a multiple regression model to predict the response using all of the predictors. Describe your results. For which predictors can we reject the null hypothesis $H_0$ : $\beta_j = 0$?</h4>

<h4>$(c)$ How do your results from $(a)$ compare to your results from $(b)$? Create a plot displaying the univariate regression coefficients from $(a)$ on the `x-axis`, and the multiple regression coefficients from $(b)$ on the `y-axis`. That is, each predictor is displayed as a single point in the plot. Its coefficient in a simple linear regression model is shown on the `x-axis`, and its coefficient estimate in the multiple linear regression model is shown on the `y-axis`.</h4>

<h4>(d) Is there evidence of non-linear association between any of the predictors and the response? To answer this question, for each predictor X, fit a model of the form $Y = \beta_{0} + \beta_{1}{X} + \beta_{2}{X}^{2} + \beta_{3}{X}^{3} + \epsilon$.</h4>